### ISSUE TITLE
Problem with set_i2c_address

### ISSUE THREAD

**Issue by josemidevel** [Abstract-Horizon/vl53l5cx_python#2]
Hi,

First, congrats for your work.

Currently I'm testing with two sensors. My problem is that I'm unable to change the default i2c address.

So, I connect the LPn pin to enable/disable the sensor, as exposed on the datasheet, to program the new address. But, when I call to set_i2c_address it gives me the following error:

Traceback (most recent call last):
  File "test_2.py", line 20, in <module>
    driver_l.set_i2c_address(62)
  File "/home/pi/.local/lib/python3.7/site-packages/vl53l5cx/vl53l5cx.py", line 745, in set_i2c_address
    self.wr_byte(0x7fff, 0x02)
  File "/home/pi/.local/lib/python3.7/site-packages/vl53l5cx/vl53l5cx.py", line 404, in wr_byte
    self._i2c_bus.i2c_rdwr(write_addr_and_value)
  File "/home/pi/.local/lib/python3.7/site-packages/smbus2/smbus2.py", line 658, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 121] Remote I/O error

This is my code:

import time
import RPi.GPIO as gpio
from vl53l5cx.vl53l5cx import VL53L5CX

gpio.setwarnings(False)
gpio.setmode(gpio.BOARD)

gpio.setup(7, gpio.OUT)

driver_l = VL53L5CX()

gpio.output(7, False)
gpio.setup(11, gpio.OUT)
gpio.output(11, True)

driver_l.set_i2c_address(62)

**Comment by natdan** [comment]
I'll try to check what is happening with it later on today or early in the morning and return back to you.

**Comment by natdan** [comment]
It seems that there's some discrepancy between how i2c works for smbus (or such) and what it does in C code. I've fixed it in the source. I'll push new (patch) version in PyPi in a moment... Let me know if it works now.

BTW wasn't sure if I have every even tried to change i2c address with VL53L5CX - I did it for up to 8 sensors for VL53L0X and VL53L1X. 

Out of curiosity - what are you planning to do with two sensors on the same bus? If you find bus being swamped it is worth considering using second i2c bus on the RPi (or on Pi4 there are 4 exposed i2c busses on GPIO pins! :D )

**Comment by josemidevel** [comment]
Wow, thanks for your quick response and patching.

Now I am out of muy home, I will test next Monday.

For me it is the first time I use the pi's i2c channel. I didn't known that
the pi has more than one i2c ports(I'm testing with a pi 3). I'll try It.

I'll keep you informed of my progress.

Thanks one more time.
